#!/usr/bin/env bash

set -euo pipefail

case "${1:-}" in
  "run")
    while true; do
      if autopi power.sleep_timer clear="*"; then
        sleep 30
      else
        sleep 3
      fi
    done
  ;;
  "on")
    $0 off
    screen -dmS caffeine -- caffeine run
    echo "caffeine on"
  ;;
  "off")
    screen -S caffeine -X quit || true
    echo "caffeine off"
  ;;
  *)
    echo "wat"
    exit 1
  ;;
esac